name: Release

on:
  push:
    branches: [main]
    paths: [deno.json, package.json]
  workflow_dispatch:
    inputs:
      version:
        description: patch, minor, major, prepatch, preminor, premajor, prerelease, or an explicit version
        required: true
        type: string

concurrency: release

jobs:
  release:
    if: github.repository == 'globalbrain/hado'
    uses: $/.github/workflows/release.reusable.yaml
    with:
      version: ${{ inputs.version }}
      publish: deno publish
      environment: jsr
      environment_url: https://jsr.io/@globalbrain/hado@{0}
    permissions:
      actions: read
      contents: write
      id-token: write
      pull-requests: write
