name: Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: brc-dd/cross-bdd/.github/workflows/test.reusable.yaml@5dd8e4745588535a78eee0c3768fffe6cfd58d44 # main
    with:
      deno_versions: latest
